# @import ../variables.http
POST /api/profile
Authorization: Bearer {{userAccessToken}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="fullName"

Dummy Name
--WebKitFormBoundary
Content-Disposition: form-data; name="mobileNumber"

9875643210
--WebKitFormBoundary
Content-Disposition: form-data; name="bio"

Dummy Bio
--WebKitFormBoundary
Content-Disposition: form-data; name="displayPicture"; filename="2.png"
Content-Type: image/png

< /home/max/Pictures/2.png
--WebKitFormBoundary--