# @import ../variables.http

POST /api/article
Authorization: Bearer {{userAccessToken}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="title"

Test Title
--WebKitFormBoundary
Content-Disposition: form-data; name="summary"

Test Summary
--WebKitFormBoundary
Content-Disposition: form-data; name="content"

<h1>Test Content</h1>
--WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="2.png"
Content-Type: image/png

< /home/max/Pictures/2.png
--WebKitFormBoundary--
