@host=https://localhost:5000
@userAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsIlVzZXJJZCI6IjIiLCJUb2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJVc2VyIiwiRGVmYXVsdCI6IkRlZmF1bHRVc2VyIiwibmJmIjoxNzQ3MTU3NTk4LCJleHAiOjE3NDc3NTc1OTgsImlhdCI6MTc0NzE1NzU5OCwiaXNzIjoibG9jYWxob3N0In0.ifIKn6KxuAduElHjVyG5nMm4JacVOSP0X49buvKQbvU
@adminAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIlVzZXJJZCI6IjEiLCJUb2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJBZG1pbiIsIkRlZmF1bHQiOiJEZWZhdWx0QWRtaW4iLCJuYmYiOjE3NDcxNjA1NzEsImV4cCI6MTc0Nzc2MDU3MSwiaWF0IjoxNzQ3MTYwNTcxLCJpc3MiOiJsb2NhbGhvc3QifQ.tMlWbgXqaXtiuOHCeGxvEAZUpPYYgupGUmmpkeEr-oE
