# @import ../variables.http

PUT /api/member/1
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer {{adminAccessToken}}

--WebKitFormBoundary
Content-Disposition: form-data; name="fullName"

Member 1 updated
--WebKitFormBoundary
Content-Disposition: form-data; name="bio"

Member 1 Bio updated
--WebKitFormBoundary
Content-Disposition: form-data; name="position"

CEO 1
--WebKitFormBoundary--
